services:
  golang-final-project:
    build:
      context: ..
      dockerfile: docker/app/Dockerfile.dev
    volumes:
      - ..:/app
    environment:
      - GIN_MODE=debug
    command: ["go", "run", "main.go"]

  migration:
    build:
      context: ..
      dockerfile: docker/app/Dockerfile.dev
    volumes:
      - ..:/app
    command: ["go", "run", "cmd/migrate.go"]
